stages:
  # - test # All jobs related for testing such as Unit Test
  - build
  - deploy

# flutter_test: # Name of the lane
#   stage: test # type of stage
#   script:
#     - flutter test # Run Flutter test
#   tags:
#     - Flutter # Tags for runner
#
flutter_build_android:
  stage: build
  before_script:
    - cd android
    - bundle install --deployment
  script:
    - bundle exec fastlane build
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
    tags:
      - Flutter1
      
deploy_android:
  stage: deploy
  before_script:
    - cd android
    - bundle install --deployment
  dependencies:
    - flutter_build_android
  script:
    - bundle exec fastlane deploy_beta
  tags:
  - Flutter1