stages:
  # - test # All jobs related for testing such as Unit Test
  - build
  - deploy

# flutter_test: # Name of the lane
#   stage: test # type of stage
#   script:
#     - flutter test # Run Flutter test
#   tags:
#     - Flutter # Tags for runner
#
flutter_build_android: #Job name
  stage: build # kind of job
  before_script:
    - flutter packages get
    - flutter clean
  script:
     - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
  tags:
    - Flutter

deploy_android:
  stage: deploy
  dependencies:
    - flutter_build_android
  script:
    - appcenter login --token $APP_CENTER_API_TOKEN
    - appcenter distribute release --app faisalnksaif/Todo --file build/app/outputs/apk/release/app-release.apk --group "beta-testers"
  tags:
    - Flutter