
default_platform(:ios)

desc "Create app on Developer portal and Store connect"
lane :create_app do
    create_app_online # produce

platform :ios do
  desc "Sync signing"
  lane :signing do

  end

  desc "Build binary"
  lane :build do
    signing
  end

  desc "Release"
  lane :release do
    build
  end
end
