default_platform(:android)
platform :android do
  desc "Build a Flutter apk"
  lane :build do
    Dir.chdir("../..") do
      sh "flutter packages get"
      sh "flutter clean"
      sh "flutter build apk"
    end
  end
  desc "Submit a new Beta Build to AppCenter"
  lane :deploy do
  if File.exist?(File.dirname(__FILE__) + "./../build/app/outputs/apk/release/app-release.apk")
    appcenter_upload(
      api_token: "17a86af1a40bf3080c65207cbd1ee5cd0f6b93f1", # Your secret api token from app center
      owner_name: "faisalnksaif", # Your username on AppCenter
      app_name: "Todo", # Your AppCenter name
      apk: "../build/app/outputs/apk/release/app-release.apk",
    )
    else
      UI.message('Unable to find apk')
    end
  end
end